services:
  # 1. Backend Uygulaması (YENİ EKLENDİ)
  backend:
    build: ./backend  # backend klasöründeki Dockerfile'ı kullanır
    container_name: eco_kitchen_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app # Koddaki değişikliği anında algılaması için
    ports:
      - "8000:8000"
    
    env_file:
      - ./backend/.env

    environment:
      - DATABASE_URL=postgresql+asyncpg://melih:gizlisifre@db:5432/sustain_db
      
    depends_on:
      - db # Veritabanı açılmadan backend açılmasın

  # 2. PostgreSQL Veritabanı
  db:
    image: postgres:15-alpine
    container_name: eco_kitchen_db
    restart: always
    environment:
      - POSTGRES_USER=melih
      - POSTGRES_PASSWORD=gizlisifre
      - POSTGRES_DB=sustain_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 3. pgAdmin (Veritabanı Arayüzü)
  pgadmin:
    image: dpage/pgadmin4
    container_name: eco_kitchen_pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: