# Run: python -m app.seed_catalog
import asyncio
from typing import List, Dict, Optional

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database import SessionLocal
from app.models.ingredient_catalog import IngredientCatalog


SEED_ITEMS: List[Dict[str, Optional[str]]] = [
    {"name": "water", "default_unit": "ml", "aliases": None},
    {"name": "milk", "default_unit": "ml", "aliases": None},
    {"name": "almond milk", "default_unit": "ml", "aliases": None},
    {"name": "soy milk", "default_unit": "ml", "aliases": None},
    {"name": "oat milk", "default_unit": "ml", "aliases": None},
    {"name": "coconut milk", "default_unit": "ml", "aliases": None},
    {"name": "buttermilk", "default_unit": "ml", "aliases": None},
    {"name": "heavy cream", "default_unit": "ml", "aliases": None},
    {"name": "light cream", "default_unit": "ml", "aliases": None},
    {"name": "yogurt", "default_unit": "g", "aliases": None},
    {"name": "greek yogurt", "default_unit": "g", "aliases": None},
    {"name": "sour cream", "default_unit": "g", "aliases": None},
    {"name": "cream cheese", "default_unit": "g", "aliases": None},
    {"name": "butter", "default_unit": "g", "aliases": None},
    {"name": "ghee", "default_unit": "g", "aliases": None},
    {"name": "cheddar cheese", "default_unit": "g", "aliases": None},
    {"name": "mozzarella cheese", "default_unit": "g", "aliases": None},
    {"name": "parmesan cheese", "default_unit": "g", "aliases": None},
    {"name": "feta cheese", "default_unit": "g", "aliases": None},
    {"name": "goat cheese", "default_unit": "g", "aliases": None},
    {"name": "ricotta cheese", "default_unit": "g", "aliases": None},
    {"name": "cottage cheese", "default_unit": "g", "aliases": None},
    {"name": "blue cheese", "default_unit": "g", "aliases": None},
    {"name": "swiss cheese", "default_unit": "g", "aliases": None},
    {"name": "provolone cheese", "default_unit": "g", "aliases": None},
    {"name": "halloumi cheese", "default_unit": "g", "aliases": None},
    {"name": "egg", "default_unit": "piece", "aliases": None},
    {"name": "egg white", "default_unit": "piece", "aliases": None},
    {"name": "egg yolk", "default_unit": "piece", "aliases": None},
    {"name": "olive oil", "default_unit": "ml", "aliases": None},
    {"name": "extra virgin olive oil", "default_unit": "ml", "aliases": None},
    {"name": "canola oil", "default_unit": "ml", "aliases": None},
    {"name": "sunflower oil", "default_unit": "ml", "aliases": None},
    {"name": "vegetable oil", "default_unit": "ml", "aliases": None},
    {"name": "coconut oil", "default_unit": "ml", "aliases": None},
    {"name": "sesame oil", "default_unit": "ml", "aliases": None},
    {"name": "avocado oil", "default_unit": "ml", "aliases": None},
    {"name": "grapeseed oil", "default_unit": "ml", "aliases": None},
    {"name": "peanut oil", "default_unit": "ml", "aliases": None},
    {"name": "white vinegar", "default_unit": "ml", "aliases": None},
    {"name": "apple cider vinegar", "default_unit": "ml", "aliases": None},
    {"name": "balsamic vinegar", "default_unit": "ml", "aliases": None},
    {"name": "red wine vinegar", "default_unit": "ml", "aliases": None},
    {"name": "rice vinegar", "default_unit": "ml", "aliases": None},
    {"name": "soy sauce", "default_unit": "ml", "aliases": None},
    {"name": "tamari", "default_unit": "ml", "aliases": None},
    {"name": "fish sauce", "default_unit": "ml", "aliases": None},
    {"name": "worcestershire sauce", "default_unit": "ml", "aliases": None},
    {"name": "hot sauce", "default_unit": "ml", "aliases": None},
    {"name": "ketchup", "default_unit": "ml", "aliases": None},
    {"name": "mustard", "default_unit": "ml", "aliases": None},
    {"name": "dijon mustard", "default_unit": "ml", "aliases": None},
    {"name": "mayonnaise", "default_unit": "ml", "aliases": None},
    {"name": "tomato paste", "default_unit": "g", "aliases": None},
    {"name": "tomato sauce", "default_unit": "ml", "aliases": None},
    {"name": "passata", "default_unit": "ml", "aliases": None},
    {"name": "salsa", "default_unit": "ml", "aliases": None},
    {"name": "barbecue sauce", "default_unit": "ml", "aliases": None},
    {"name": "teriyaki sauce", "default_unit": "ml", "aliases": None},
    {"name": "hoisin sauce", "default_unit": "ml", "aliases": None},
    {"name": "oyster sauce", "default_unit": "ml", "aliases": None},
    {"name": "chili sauce", "default_unit": "ml", "aliases": None},
    {"name": "chicken stock", "default_unit": "ml", "aliases": None},
    {"name": "beef stock", "default_unit": "ml", "aliases": None},
    {"name": "vegetable stock", "default_unit": "ml", "aliases": None},
    {"name": "bone broth", "default_unit": "ml", "aliases": None},
    {"name": "sugar", "default_unit": "g", "aliases": None},
    {"name": "brown sugar", "default_unit": "g", "aliases": None},
    {"name": "powdered sugar", "default_unit": "g", "aliases": None},
    {"name": "honey", "default_unit": "g", "aliases": None},
    {"name": "maple syrup", "default_unit": "ml", "aliases": None},
    {"name": "agave syrup", "default_unit": "ml", "aliases": None},
    {"name": "molasses", "default_unit": "g", "aliases": None},
    {"name": "corn syrup", "default_unit": "ml", "aliases": None},
    {"name": "flour", "default_unit": "g", "aliases": None},
    {"name": "all purpose flour", "default_unit": "g", "aliases": None},
    {"name": "bread flour", "default_unit": "g", "aliases": None},
    {"name": "whole wheat flour", "default_unit": "g", "aliases": None},
    {"name": "cake flour", "default_unit": "g", "aliases": None},
    {"name": "cornmeal", "default_unit": "g", "aliases": None},
    {"name": "semolina", "default_unit": "g", "aliases": None},
    {"name": "baking powder", "default_unit": "g", "aliases": None},
    {"name": "baking soda", "default_unit": "g", "aliases": None},
    {"name": "yeast", "default_unit": "g", "aliases": None},
    {"name": "instant yeast", "default_unit": "g", "aliases": None},
    {"name": "active dry yeast", "default_unit": "g", "aliases": None},
    {"name": "cocoa powder", "default_unit": "g", "aliases": None},
    {"name": "chocolate", "default_unit": "g", "aliases": None},
    {"name": "dark chocolate", "default_unit": "g", "aliases": None},
    {"name": "milk chocolate", "default_unit": "g", "aliases": None},
    {"name": "white chocolate", "default_unit": "g", "aliases": None},
    {"name": "vanilla extract", "default_unit": "ml", "aliases": None},
    {"name": "vanilla", "default_unit": "g", "aliases": None},
    {"name": "gelatin", "default_unit": "g", "aliases": None},
    {"name": "cornstarch", "default_unit": "g", "aliases": None},
    {"name": "tapioca starch", "default_unit": "g", "aliases": None},
    {"name": "arrowroot", "default_unit": "g", "aliases": None},
    {"name": "cream of tartar", "default_unit": "g", "aliases": None},
    {"name": "baking chocolate", "default_unit": "g", "aliases": None},
    {"name": "rice", "default_unit": "g", "aliases": None},
    {"name": "basmati rice", "default_unit": "g", "aliases": None},
    {"name": "jasmine rice", "default_unit": "g", "aliases": None},
    {"name": "brown rice", "default_unit": "g", "aliases": None},
    {"name": "arborio rice", "default_unit": "g", "aliases": None},
    {"name": "wild rice", "default_unit": "g", "aliases": None},
    {"name": "quinoa", "default_unit": "g", "aliases": None},
    {"name": "bulgur", "default_unit": "g", "aliases": None},
    {"name": "couscous", "default_unit": "g", "aliases": None},
    {"name": "oats", "default_unit": "g", "aliases": None},
    {"name": "rolled oats", "default_unit": "g", "aliases": None},
    {"name": "steel cut oats", "default_unit": "g", "aliases": None},
    {"name": "barley", "default_unit": "g", "aliases": None},
    {"name": "farro", "default_unit": "g", "aliases": None},
    {"name": "millet", "default_unit": "g", "aliases": None},
    {"name": "polenta", "default_unit": "g", "aliases": None},
    {"name": "pasta", "default_unit": "g", "aliases": None},
    {"name": "spaghetti", "default_unit": "g", "aliases": None},
    {"name": "penne", "default_unit": "g", "aliases": None},
    {"name": "fusilli", "default_unit": "g", "aliases": None},
    {"name": "macaroni", "default_unit": "g", "aliases": None},
    {"name": "lasagna noodles", "default_unit": "g", "aliases": None},
    {"name": "rice noodles", "default_unit": "g", "aliases": None},
    {"name": "soba noodles", "default_unit": "g", "aliases": None},
    {"name": "udon noodles", "default_unit": "g", "aliases": None},
    {"name": "ramen noodles", "default_unit": "g", "aliases": None},
    {"name": "orzo", "default_unit": "g", "aliases": None},
    {"name": "gnocchi", "default_unit": "g", "aliases": None},
    {"name": "bread", "default_unit": "piece", "aliases": None},
    {"name": "baguette", "default_unit": "piece", "aliases": None},
    {"name": "bagel", "default_unit": "piece", "aliases": None},
    {"name": "tortilla", "default_unit": "piece", "aliases": None},
    {"name": "pita", "default_unit": "piece", "aliases": None},
    {"name": "naan", "default_unit": "piece", "aliases": None},
    {"name": "breadcrumbs", "default_unit": "g", "aliases": None},
    {"name": "panko", "default_unit": "g", "aliases": None},
    {"name": "cracker", "default_unit": "g", "aliases": None},
    {"name": "lentils", "default_unit": "g", "aliases": None},
    {"name": "red lentils", "default_unit": "g", "aliases": None},
    {"name": "green lentils", "default_unit": "g", "aliases": None},
    {"name": "black beans", "default_unit": "g", "aliases": None},
    {"name": "kidney beans", "default_unit": "g", "aliases": None},
    {"name": "pinto beans", "default_unit": "g", "aliases": None},
    {"name": "white beans", "default_unit": "g", "aliases": None},
    {"name": "navy beans", "default_unit": "g", "aliases": None},
    {"name": "cannellini beans", "default_unit": "g", "aliases": None},
    {"name": "chickpeas", "default_unit": "g", "aliases": None},
    {"name": "split peas", "default_unit": "g", "aliases": None},
    {"name": "edamame", "default_unit": "g", "aliases": None},
    {"name": "soybeans", "default_unit": "g", "aliases": None},
    {"name": "chicken breast", "default_unit": "g", "aliases": None},
    {"name": "chicken thigh", "default_unit": "g", "aliases": None},
    {"name": "chicken drumstick", "default_unit": "g", "aliases": None},
    {"name": "chicken wing", "default_unit": "g", "aliases": None},
    {"name": "whole chicken", "default_unit": "g", "aliases": None},
    {"name": "turkey breast", "default_unit": "g", "aliases": None},
    {"name": "ground turkey", "default_unit": "g", "aliases": None},
    {"name": "beef", "default_unit": "g", "aliases": None},
    {"name": "ground beef", "default_unit": "g", "aliases": None},
    {"name": "beef steak", "default_unit": "g", "aliases": None},
    {"name": "pork", "default_unit": "g", "aliases": None},
    {"name": "pork belly", "default_unit": "g", "aliases": None},
    {"name": "pork chops", "default_unit": "g", "aliases": None},
    {"name": "bacon", "default_unit": "g", "aliases": None},
    {"name": "ham", "default_unit": "g", "aliases": None},
    {"name": "sausage", "default_unit": "g", "aliases": None},
    {"name": "chorizo", "default_unit": "g", "aliases": None},
    {"name": "lamb", "default_unit": "g", "aliases": None},
    {"name": "lamb chops", "default_unit": "g", "aliases": None},
    {"name": "veal", "default_unit": "g", "aliases": None},
    {"name": "salmon", "default_unit": "g", "aliases": None},
    {"name": "tuna", "default_unit": "g", "aliases": None},
    {"name": "cod", "default_unit": "g", "aliases": None},
    {"name": "tilapia", "default_unit": "g", "aliases": None},
    {"name": "trout", "default_unit": "g", "aliases": None},
    {"name": "shrimp", "default_unit": "g", "aliases": None},
    {"name": "scallop", "default_unit": "g", "aliases": None},
    {"name": "mussel", "default_unit": "g", "aliases": None},
    {"name": "clam", "default_unit": "g", "aliases": None},
    {"name": "squid", "default_unit": "g", "aliases": None},
    {"name": "octopus", "default_unit": "g", "aliases": None},
    {"name": "crab", "default_unit": "g", "aliases": None},
    {"name": "tomato", "default_unit": "piece", "aliases": None},
    {"name": "cherry tomato", "default_unit": "piece", "aliases": None},
    {"name": "onion", "default_unit": "piece", "aliases": None},
    {"name": "yellow onion", "default_unit": "piece", "aliases": None},
    {"name": "white onion", "default_unit": "piece", "aliases": None},
    {"name": "red onion", "default_unit": "piece", "aliases": None},
    {"name": "shallot", "default_unit": "piece", "aliases": None},
    {"name": "scallion", "default_unit": "piece", "aliases": "green onion"},
    {"name": "leek", "default_unit": "piece", "aliases": None},
    {"name": "garlic", "default_unit": "piece", "aliases": None},
    {"name": "ginger", "default_unit": "g", "aliases": None},
    {"name": "potato", "default_unit": "piece", "aliases": None},
    {"name": "sweet potato", "default_unit": "piece", "aliases": None},
    {"name": "carrot", "default_unit": "piece", "aliases": None},
    {"name": "celery", "default_unit": "piece", "aliases": None},
    {"name": "cucumber", "default_unit": "piece", "aliases": None},
    {"name": "zucchini", "default_unit": "piece", "aliases": None},
    {"name": "eggplant", "default_unit": "piece", "aliases": None},
    {"name": "bell pepper", "default_unit": "piece", "aliases": None},
    {"name": "green pepper", "default_unit": "piece", "aliases": None},
    {"name": "red pepper", "default_unit": "piece", "aliases": None},
    {"name": "yellow pepper", "default_unit": "piece", "aliases": None},
    {"name": "jalapeno", "default_unit": "piece", "aliases": None},
    {"name": "serrano pepper", "default_unit": "piece", "aliases": None},
    {"name": "poblano pepper", "default_unit": "piece", "aliases": None},
    {"name": "chili pepper", "default_unit": "piece", "aliases": None},
    {"name": "cabbage", "default_unit": "piece", "aliases": None},
    {"name": "red cabbage", "default_unit": "piece", "aliases": None},
    {"name": "napa cabbage", "default_unit": "piece", "aliases": None},
    {"name": "bok choy", "default_unit": "piece", "aliases": None},
    {"name": "kale", "default_unit": "g", "aliases": None},
    {"name": "spinach", "default_unit": "g", "aliases": None},
    {"name": "arugula", "default_unit": "g", "aliases": None},
    {"name": "lettuce", "default_unit": "piece", "aliases": None},
    {"name": "romaine lettuce", "default_unit": "piece", "aliases": None},
    {"name": "iceberg lettuce", "default_unit": "piece", "aliases": None},
    {"name": "broccoli", "default_unit": "piece", "aliases": None},
    {"name": "cauliflower", "default_unit": "piece", "aliases": None},
    {"name": "brussels sprouts", "default_unit": "g", "aliases": None},
    {"name": "green beans", "default_unit": "g", "aliases": None},
    {"name": "asparagus", "default_unit": "g", "aliases": None},
    {"name": "peas", "default_unit": "g", "aliases": None},
    {"name": "corn", "default_unit": "g", "aliases": None},
    {"name": "mushroom", "default_unit": "g", "aliases": None},
    {"name": "button mushroom", "default_unit": "g", "aliases": None},
    {"name": "cremini mushroom", "default_unit": "g", "aliases": None},
    {"name": "shiitake mushroom", "default_unit": "g", "aliases": None},
    {"name": "portobello mushroom", "default_unit": "g", "aliases": None},
    {"name": "beet", "default_unit": "piece", "aliases": None},
    {"name": "radish", "default_unit": "piece", "aliases": None},
    {"name": "turnip", "default_unit": "piece", "aliases": None},
    {"name": "parsnip", "default_unit": "piece", "aliases": None},
    {"name": "pumpkin", "default_unit": "piece", "aliases": None},
    {"name": "butternut squash", "default_unit": "piece", "aliases": None},
    {"name": "acorn squash", "default_unit": "piece", "aliases": None},
    {"name": "spaghetti squash", "default_unit": "piece", "aliases": None},
    {"name": "artichoke", "default_unit": "piece", "aliases": None},
    {"name": "okra", "default_unit": "g", "aliases": None},
    {"name": "fennel", "default_unit": "piece", "aliases": None},
    {"name": "avocado", "default_unit": "piece", "aliases": None},
    {"name": "olive", "default_unit": "g", "aliases": None},
    {"name": "capers", "default_unit": "g", "aliases": None},
    {"name": "pickles", "default_unit": "g", "aliases": None},
    {"name": "parsley", "default_unit": "g", "aliases": None},
    {"name": "cilantro", "default_unit": "g", "aliases": None},
    {"name": "basil", "default_unit": "g", "aliases": None},
    {"name": "mint", "default_unit": "g", "aliases": None},
    {"name": "dill", "default_unit": "g", "aliases": None},
    {"name": "thyme", "default_unit": "g", "aliases": None},
    {"name": "oregano", "default_unit": "g", "aliases": None},
    {"name": "rosemary", "default_unit": "g", "aliases": None},
    {"name": "sage", "default_unit": "g", "aliases": None},
    {"name": "tarragon", "default_unit": "g", "aliases": None},
    {"name": "chives", "default_unit": "g", "aliases": None},
    {"name": "bay leaf", "default_unit": "piece", "aliases": None},
    {"name": "lemongrass", "default_unit": "piece", "aliases": None},
    {"name": "salt", "default_unit": "g", "aliases": None},
    {"name": "sea salt", "default_unit": "g", "aliases": None},
    {"name": "kosher salt", "default_unit": "g", "aliases": None},
    {"name": "black pepper", "default_unit": "g", "aliases": None},
    {"name": "white pepper", "default_unit": "g", "aliases": None},
    {"name": "paprika", "default_unit": "g", "aliases": None},
    {"name": "smoked paprika", "default_unit": "g", "aliases": None},
    {"name": "cayenne pepper", "default_unit": "g", "aliases": None},
    {"name": "chili powder", "default_unit": "g", "aliases": None},
    {"name": "cumin", "default_unit": "g", "aliases": None},
    {"name": "coriander", "default_unit": "g", "aliases": None},
    {"name": "turmeric", "default_unit": "g", "aliases": None},
    {"name": "cinnamon", "default_unit": "g", "aliases": None},
    {"name": "nutmeg", "default_unit": "g", "aliases": None},
    {"name": "cloves", "default_unit": "g", "aliases": None},
    {"name": "allspice", "default_unit": "g", "aliases": None},
    {"name": "cardamom", "default_unit": "g", "aliases": None},
    {"name": "star anise", "default_unit": "piece", "aliases": None},
    {"name": "mustard seed", "default_unit": "g", "aliases": None},
    {"name": "fennel seed", "default_unit": "g", "aliases": None},
    {"name": "sesame seed", "default_unit": "g", "aliases": None},
    {"name": "poppy seed", "default_unit": "g", "aliases": None},
    {"name": "chia seed", "default_unit": "g", "aliases": None},
    {"name": "flaxseed", "default_unit": "g", "aliases": None},
    {"name": "hemp seed", "default_unit": "g", "aliases": None},
    {"name": "pumpkin seed", "default_unit": "g", "aliases": None},
    {"name": "sunflower seed", "default_unit": "g", "aliases": None},
    {"name": "almond", "default_unit": "g", "aliases": None},
    {"name": "walnut", "default_unit": "g", "aliases": None},
    {"name": "pecan", "default_unit": "g", "aliases": None},
    {"name": "hazelnut", "default_unit": "g", "aliases": None},
    {"name": "pistachio", "default_unit": "g", "aliases": None},
    {"name": "cashew", "default_unit": "g", "aliases": None},
    {"name": "macadamia", "default_unit": "g", "aliases": None},
    {"name": "peanut", "default_unit": "g", "aliases": None},
    {"name": "coconut flakes", "default_unit": "g", "aliases": None},
    {"name": "apple", "default_unit": "piece", "aliases": None},
    {"name": "banana", "default_unit": "piece", "aliases": None},
    {"name": "orange", "default_unit": "piece", "aliases": None},
    {"name": "lemon", "default_unit": "piece", "aliases": None},
    {"name": "lime", "default_unit": "piece", "aliases": None},
    {"name": "grapefruit", "default_unit": "piece", "aliases": None},
    {"name": "strawberry", "default_unit": "g", "aliases": None},
    {"name": "blueberry", "default_unit": "g", "aliases": None},
    {"name": "raspberry", "default_unit": "g", "aliases": None},
    {"name": "blackberry", "default_unit": "g", "aliases": None},
    {"name": "cherry", "default_unit": "g", "aliases": None},
    {"name": "grape", "default_unit": "g", "aliases": None},
    {"name": "pineapple", "default_unit": "piece", "aliases": None},
    {"name": "mango", "default_unit": "piece", "aliases": None},
    {"name": "papaya", "default_unit": "piece", "aliases": None},
    {"name": "kiwi", "default_unit": "piece", "aliases": None},
    {"name": "pear", "default_unit": "piece", "aliases": None},
    {"name": "peach", "default_unit": "piece", "aliases": None},
    {"name": "plum", "default_unit": "piece", "aliases": None},
    {"name": "apricot", "default_unit": "piece", "aliases": None},
    {"name": "fig", "default_unit": "piece", "aliases": None},
    {"name": "date", "default_unit": "g", "aliases": None},
    {"name": "raisin", "default_unit": "g", "aliases": None},
    {"name": "cranberry", "default_unit": "g", "aliases": None},
    {"name": "pomegranate", "default_unit": "piece", "aliases": None},
    {"name": "watermelon", "default_unit": "piece", "aliases": None},
    {"name": "cantaloupe", "default_unit": "piece", "aliases": None},
    {"name": "honeydew", "default_unit": "piece", "aliases": None},
    {"name": "tofu", "default_unit": "g", "aliases": None},
    {"name": "tempeh", "default_unit": "g", "aliases": None},
    {"name": "seitan", "default_unit": "g", "aliases": None},
    {"name": "miso paste", "default_unit": "g", "aliases": None},
    {"name": "curry paste", "default_unit": "g", "aliases": None},
    {"name": "pesto", "default_unit": "ml", "aliases": None},
    {"name": "hummus", "default_unit": "g", "aliases": None},
    {"name": "tahini", "default_unit": "g", "aliases": None},
    {"name": "coconut sugar", "default_unit": "g", "aliases": None},
    {"name": "coffee", "default_unit": "g", "aliases": None},
    {"name": "tea", "default_unit": "g", "aliases": None},
]


async def seed_catalog(session: AsyncSession) -> int:
    names = [item["name"] for item in SEED_ITEMS]
    result = await session.execute(
        select(IngredientCatalog.name).where(IngredientCatalog.name.in_(names))
    )
    existing = {row[0] for row in result.all()}

    to_add = [
        IngredientCatalog(**item)
        for item in SEED_ITEMS
        if item["name"] not in existing
    ]

    if not to_add:
        return 0

    session.add_all(to_add)
    await session.commit()
    return len(to_add)


async def main() -> None:
    async with SessionLocal() as session:
        count = await seed_catalog(session)
        print(f"Seeded {count} catalog items.")


if __name__ == "__main__":
    asyncio.run(main())
